lnguageCode = "zh_CN"
title = "Aaron's Notes"
baseurl = "https://yike5460.github.io"
paginate = 5
DisqusShortname = "Aaron"
Copyright = "All rights reserved - 2019"
canonifyurls = true 
[params]
  description = "Notes for Cloud"
  #cover = "images/cover.jpg"
  author = "Aaron"
  autobio= "Used to be a Coder"
  authorlocation = "Beijing, China"
  authorwebsite = "https://yike5460.github.io"
  #logo = "images/Einstan.jpg"
  #googleAnalyticsUserID = "UA-79101-12" 
  #Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "yike5460"
  #twitterName = "lovebao0917" 
  #facebookName = ""
  linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  #[params.social]
    #linkedin = "https://cn.linkedin.com"
	
[[menu.main]]
  name = "Aaron's Notes"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
